name: Scheduled update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install python3-venv and firefox
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv firefox
    #- name: Install poetry
    #  uses: abatilo/actions-poetry@v2.0.0
    #  with:
    #    poetry-version: 1.1.0
    - name: Install dependencies
      run: |
        pip install selenium==4.2.0 pandas python-dotenv arrow matplotlib
        pip install git+https://github.com/zaironjacobs/get-gecko-driver@main#egg=get_gecko_driver
        get-gecko-driver --download-latest --extract    
    #- name: Poetry install
    #  run: |
    #    poetry install
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Run scraper
      run: |
        python -m panel convert notebooks/index.ipynb --to pyodide-worker --out docs --pwa --title "Ontario grid data"
    - name: Commit
      continue-on-error: true
      run: |
        # Stage the file, commit and push
        git add notebooks/index.ipynb docs
        git commit -m "build docs"
        git push origin main
